//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangDiem
    {
        public string maSinhVien { get; set; }
        public string maLopMonHoc { get; set; }
        public string trangThai { get; set; }
        public Nullable<decimal> thucHanh { get; set; }
        public Nullable<decimal> giuaKy { get; set; }
        public Nullable<decimal> cuoiKy { get; set; }
        public Nullable<decimal> thuongKy { get; set; }
    
        public virtual LopMonHoc LopMonHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
