//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GiangVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiangVien()
        {
            this.LopMonHocs = new HashSet<LopMonHoc>();
        }

        [Display(Name = "Mã giảng viên")]
        public string maGiangVien { get; set; }
        [Display(Name = "Tên giảng viên")]
        public string tenGiangVien { get; set; }
        [Display(Name ="Quê quán")]
        public string queQuan { get; set; }
        [Display(Name = "Ngày sinh")]
        public Nullable<System.DateTime> ngaySinh { get; set; }
        [Display(Name = "Năm bắt đầu")]
        public Nullable<int> namBatDau { get; set; }
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Phải đúng định dạng email")]
        public string eMail { get; set; }
        [Display(Name = "Tên đăng nhập")]
        public string tenDangNhap { get; set; }
        [Display(Name = "Mã bài viết")]
        public string maBaiViet { get; set; }
    
        public virtual BaiViet BaiViet { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopMonHoc> LopMonHocs { get; set; }
    }
}
