//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopMonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopMonHoc()
        {
            this.BangDiems = new HashSet<BangDiem>();
        }
    
        public string maLopMonHoc { get; set; }
        public string tenLopMonHoc { get; set; }
        public string maMonHoc { get; set; }
        public Nullable<int> soLuongToiDa { get; set; }
        public Nullable<int> soLuongDangKy { get; set; }
        public string maGiangVien { get; set; }
        public string trangThai { get; set; }
        public Nullable<int> namHoc { get; set; }
        public Nullable<int> hocKy { get; set; }
        public string phongHoc { get; set; }
        public Nullable<int> tietHocTu { get; set; }
        public Nullable<int> tietHocDen { get; set; }
        public Nullable<int> ngayHoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangDiem> BangDiems { get; set; }
        public virtual GiangVien GiangVien { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
