//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Models.Data
{
    using System;
    
    public partial class MM
    {
        public string maMonHoc { get; set; }
        public string tenMonHoc { get; set; }
        public string maChuyenNganh { get; set; }
        public Nullable<int> soTinChi { get; set; }
        public string trangThai { get; set; }
    }
}
